input_dataset_name: droid_dataset
dataset_type: RLDS

output_dataset:
  name: DROID
  tags: [panda, in-the-wild, manipulation, table-top, kitchen]
  description: "DROID is a large-scale, open-source robot manipulation dataset featuring 76k trajectories across diverse, real-world scenes to improve robotic policy generalization."

robot: 
  name: franka_panda
  urdf_path: "panda.urdf"
  override_existing: true

frequency: 15.0

data_import_config:
  RGB_IMAGES:
    source: observation
    format:
      image_convention: CHANNELS_LAST
      order_of_channels: RGB
    mapping: 
      - name: wrist_image_left
        source_name: wrist_image_left
      - name: exterior_image_1_left
        source_name: exterior_image_1_left
      - name: exterior_image_2_left
        source_name: exterior_image_2_left

  JOINT_POSITIONS: 
    source: observation.joint_position
    mapping:
      - name: panda_joint1
      - name: panda_joint2
      - name: panda_joint3
      - name: panda_joint4
      - name: panda_joint5
      - name: panda_joint6
      - name: panda_joint7
    
  JOINT_TARGET_POSITIONS:
    source: action_dict.joint_position
    mapping:
      - name: panda_joint1
      - name: panda_joint2
      - name: panda_joint3
      - name: panda_joint4
      - name: panda_joint5
      - name: panda_joint6
      - name: panda_joint7

  PARALLEL_GRIPPER_OPEN_AMOUNTS:
    source: observation.gripper_position
    format:
      invert_gripper_amount: true
    mapping:
      - name: gripper
        index: 0
  
  PARALLEL_GRIPPER_TARGET_OPEN_AMOUNTS:
    source: action_dict.gripper_position
    format:
      invert_gripper_amount: true
    mapping:
      - name: gripper
        index: 0

  VISUAL_JOINT_POSITIONS:
    source: observation.gripper_position
    format:
      visual_joint_type: GRIPPER
      invert_gripper_amount: true
    mapping:
      - name: panda_finger_joint1
        index: 0
      - name: panda_finger_joint2
        index: 0

  LANGUAGE:
    format:
      language_type: BYTES
    mapping:
      - name: instruction1
        source_name: language_instruction
      - name: instruction2
        source_name: language_instruction_2
      - name: instruction3
        source_name: language_instruction_3