input_dataset_name: lerobot/nyu_franka_play_dataset
dataset_type: LEROBOT
output_dataset:
  name: NYU_franka_play
  tags: [unitree, humanoid, folding, clothes, manipulation]
  description: "This dataset contains images and sensor data collected from the LeRobot Unitree H1 robot while performing fold clothes tasks in an indoor environment."

robot:
  name: nyu_franka
  mjcf_path: "panda.urdf"

frequency: 50

data_import_config: 
  RGB_IMAGES:
    source: observation.images
    format:
      image_convention: CHANNELS_FIRST
      order_of_channels: RGB
      normalized_pixel_values: TRUE
    mapping: 
      - name: image
        source_name: image
      - name: additional
        source_name: image_additional_view
      

  JOINT_POSITIONS: 
    source: observation.state
    units: RADIANS
    mapping:
      - name: panda_joint1
        index: 0
      - name: panda_joint2
        index: 1
      - name: panda_joint3
        index: 2
      - name: panda_joint4
        index: 3
      - name: panda_joint5
        index: 4
      - name: panda_joint6
        index: 5
      - name: panda_joint7
        index: 6
      - name: panda_joint8
        index: 7
      - name: panda_hand_joint
        index: 7
      - name: panda_hand_tcp_joint
        index: 7
      - name: panda_finger_joint1
        index: 7
      - name: panda_finger_joint2
        index: 7

  LANGUAGE:
    source: task
    format:
      language_type: STRING
    mapping:
      - name: instruction