# @package _global_
algorithm:
  _target_: neuracore.ml.algorithms.cnnmlp.cnnmlp.CNNMLP
  image_backbone: "resnet18"
  use_resnet_stats: true
  hidden_dim: 512
  cnn_output_dim: 512
  num_layers: 3
  lr: 1e-4
  freeze_backbone: false
  lr_backbone: 1e-5
  weight_decay: 1e-4